/* Used for common .env variables */
const BACKEND_API = process.env.NEXT_PUBLIC_BACKEND_API_URL
const FRONTEND_URL = process.env.NEXT_PUBLIC_FRONTEND_URL
const REDIRECT_URI = process.env.NEXT_PUBLIC_REDIRECT_URI
const GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY

export { BACKEND_API, FRONTEND_URL, REDIRECT_URI, GOOGLE_MAPS_API_KEY }
